# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

WORKDIR /app

# Install FastMCP dependency
RUN pip install --no-cache-dir fastmcp>=2.11.3

# Copy application code
COPY main.py .

# Launch the MCP server
ENTRYPOINT ["python", "main.py"]
